- hosts: all

  tasks:
    - name: Upgrade Hosts (Ubuntu)
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
